language: php
php:
  - '5.5'
before_install:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
install:
  - 'npm install'
  - 'bower install'
  - 'composer install'

branches:
	only:
		- 'master'
